version: "cygwin-{build}"

shallow_clone: true

environment:
  matrix:
    - ARCH: x86
      CYGWIN: C:\Cygwin
      CYGSH: C:\Cygwin\bin\bash -lc
    - ARCH: x86_64
      CYGWIN: C:\Cygwin64
      CYGSH: C:\Cygwin64\bin\bash -lc

build_script:
  - "%CYGWIN%\\setup-%ARCH%.exe -q"
  - "%CYGSH% 'cd /cygdrive/c/projects/binaries ; ./build.sh'"

artifacts:
  - name: packages-swath
    path: packages
    type: zip
